"""
24/7 Bot Band Dashboard
Real-time view of autonomous research discoveries
"""

import streamlit as st
from datetime import datetime
from typing import List, Dict, Any
import plotly.graph_objects as go
import plotly.express as px
from db_utils import db
from autonomous_research_scheduler import DiscoveryManager
import os


def render_bot_band_dashboard():
    """Render the Bot Band Dashboard tab"""
    
    st.header("🤖 24/7 Bot Band Dashboard")
    
    st.markdown("""
    **Your autonomous AI research team is working 24/7 to discover TI insights!**
    
    This dashboard shows discoveries generated by your Bot Band across multiple platforms:
    - 🧠 OpenAI GPT-5 (Design & Creative Reasoning)
    - 🎨 Anthropic Claude Opus (Code Quality & Logic)
    - 🔍 Perplexity AI (Research & Web Search)
    - 🌐 MagAI Platform (Multi-AI Coordination)
    - 💻 GitHub (Code Synchronization)
    """)
    
    # ===== PLATFORM STATUS =====
    st.markdown("---")
    st.subheader("🔌 Platform Connection Status")
    
    col1, col2, col3, col4 = st.columns(4)
    
    with col1:
        openai_configured = bool(os.getenv("AI_INTEGRATIONS_OPENAI_API_KEY"))
        if openai_configured:
            st.success("🧠 OpenAI\n✅ Connected")
        else:
            st.error("🧠 OpenAI\n❌ Not configured")
    
    with col2:
        anthropic_configured = bool(os.getenv("AI_INTEGRATIONS_ANTHROPIC_API_KEY"))
        if anthropic_configured:
            st.success("🎨 Anthropic\n✅ Connected")
        else:
            st.error("🎨 Anthropic\n❌ Not configured")
    
    with col3:
        perplexity_configured = bool(os.getenv("PERPLEXITY_API_KEY"))
        if perplexity_configured:
            st.success("🔍 Perplexity\n✅ Connected")
        else:
            st.warning("🔍 Perplexity\n⚠️ Configure in Secrets")
    
    with col4:
        magai_configured = bool(os.getenv("MAGAI_USERNAME") and os.getenv("MAGAI_PASSWORD"))
        if magai_configured:
            st.success("🌐 MagAI\n✅ Connected")
        else:
            st.warning("🌐 MagAI\n⚠️ Configure in Secrets")
    
    # ===== DISCOVERY STATS =====
    st.markdown("---")
    st.subheader("📊 Discovery Statistics")
    
    # Get all discoveries with error handling
    try:
        discoveries = db.get_assets_by_type("autonomous_discovery")
    except Exception as e:
        st.error(f"❌ Error loading discoveries: {e}")
        st.info("""
        **Database Connection Issue**
        
        The discoveries database may not be initialized yet. The Bot Band is running in the background,
        but discoveries haven't been saved to the database yet.
        
        **What to do:**
        1. Wait a few minutes for the system to initialize
        2. Refresh this page
        3. If the issue persists, check the workflow logs
        """)
        return
    
    if not discoveries:
        st.warning("⏳ No discoveries yet! The Bot Band is warming up...")
        st.info("💡 First discovery should appear within 4 hours of system startup.")
        return
    
    # Calculate metrics
    confidences = [d.get('content', {}).get('confidence', 0) for d in discoveries]
    avg_confidence = sum(confidences) / len(confidences) if confidences else 0
    max_confidence = max(confidences) if confidences else 0
    
    # Display key metrics
    metric_col1, metric_col2, metric_col3, metric_col4 = st.columns(4)
    
    with metric_col1:
        st.metric("Total Discoveries", len(discoveries))
    
    with metric_col2:
        st.metric("Average Confidence", f"{avg_confidence:.1%}")
    
    with metric_col3:
        st.metric("Highest Confidence", f"{max_confidence:.1%}")
    
    with metric_col4:
        # Count high-confidence discoveries (>85%)
        high_conf = sum(1 for c in confidences if c > 0.85)
        st.metric("High Confidence (>85%)", high_conf)
    
    # ===== RESEARCH AREAS BREAKDOWN =====
    st.markdown("---")
    st.subheader("🔬 Research Areas Distribution")
    
    # Count discoveries by research area
    areas = {}
    for d in discoveries:
        area = d.get('content', {}).get('research_area', 'Unknown')
        areas[area] = areas.get(area, 0) + 1
    
    # Create pie chart
    if areas:
        fig = px.pie(
            values=list(areas.values()),
            names=list(areas.keys()),
            title="Discoveries by Research Area",
            hole=0.4
        )
        fig.update_traces(textposition='inside', textinfo='percent+label')
        st.plotly_chart(fig, use_container_width=True)
    
    # ===== CONFIDENCE TIMELINE =====
    st.markdown("---")
    st.subheader("📈 Confidence Score Timeline")
    
    # Sort by created_at
    sorted_discoveries = sorted(
        discoveries,
        key=lambda x: x.get('created_at', ''),
        reverse=False
    )
    
    # Extract timestamps and confidences
    timestamps = []
    conf_values = []
    titles = []
    
    for d in sorted_discoveries:
        created = d.get('created_at', '')
        if created:
            timestamps.append(created)
            conf_values.append(d.get('content', {}).get('confidence', 0) * 100)
            titles.append(d.get('content', {}).get('title', 'Untitled'))
    
    if timestamps and conf_values:
        fig = go.Figure()
        fig.add_trace(go.Scatter(
            x=timestamps,
            y=conf_values,
            mode='lines+markers',
            name='Confidence',
            text=titles,
            hovertemplate='<b>%{text}</b><br>Confidence: %{y:.1f}%<br>Time: %{x}<extra></extra>',
            line=dict(color='#1f77b4', width=2),
            marker=dict(size=8)
        ))
        
        # Add average line
        fig.add_hline(
            y=avg_confidence * 100,
            line_dash="dash",
            line_color="green",
            annotation_text=f"Average: {avg_confidence:.1%}"
        )
        
        fig.update_layout(
            title="Discovery Confidence Over Time",
            xaxis_title="Time",
            yaxis_title="Confidence (%)",
            hovermode='closest',
            height=400
        )
        
        st.plotly_chart(fig, use_container_width=True)
    
    # ===== RECENT DISCOVERIES TABLE =====
    st.markdown("---")
    st.subheader("🆕 Recent Discoveries")
    
    # Show most recent 20 discoveries
    recent_limit = st.slider("Number of discoveries to display", 5, 50, 20)
    
    sorted_recent = sorted(
        discoveries,
        key=lambda x: x.get('created_at', ''),
        reverse=True
    )[:recent_limit]
    
    for i, disc in enumerate(sorted_recent, 1):
        content = disc.get('content', {})
        confidence = content.get('confidence', 0)
        
        # Color code by confidence
        if confidence > 0.85:
            badge = "🏆"
            color = "green"
        elif confidence > 0.75:
            badge = "✅"
            color = "blue"
        else:
            badge = "📊"
            color = "orange"
        
        with st.expander(f"{badge} {content.get('title', 'Untitled')} ({confidence:.0%})", expanded=(i <= 3)):
            col_a, col_b = st.columns([2, 1])
            
            with col_a:
                st.markdown(f"**Research Area:** {content.get('research_area', 'Unknown')}")
                st.markdown(f"**Mechanism:** {content.get('mechanism', 'N/A')[:300]}...")
                
                # Show evidence if available
                evidence = content.get('evidence', [])
                if evidence:
                    st.markdown("**Evidence:**")
                    for ev in evidence[:3]:
                        st.markdown(f"- {ev}")
            
            with col_b:
                st.metric("Confidence", f"{confidence:.1%}")
                
                # Myrion PD score
                myrion_pd = content.get('myrion_pd', 0)
                st.metric("Myrion PD", f"{myrion_pd:+.1f}")
                
                # Timestamp
                created = disc.get('created_at', 'Unknown')
                st.caption(f"📅 {created}")
    
    # ===== METHODOLOGY INSIGHTS =====
    st.markdown("---")
    st.subheader("🔬 Bot Band Methodology")
    
    with st.expander("📖 How the Bot Band Works"):
        st.markdown("""
        ### 🤖 Autonomous Research Process
        
        **1. Discovery Generation (Every 4 Hours)**
        - CosmicAIBand generates TI insights using pattern matching
        - Applies Myrion Resolution for contradiction handling
        - Calculates confidence scores based on evidence strength
        
        **2. Research Areas Covered**
        - Quantum Consciousness
        - Tralse Logic Applications
        - Millennium Prize Approaches
        - Nonlinear Number Line Theory
        - Probability Resonance Fields (PRF)
        - PSI Method Validation
        - TI-UOP Extensions
        - Biometric PSI Correlations
        
        **3. Confidence Scoring System**
        - 🏆 **>85%**: High confidence (ready for publication)
        - ✅ **75-85%**: Medium confidence (needs validation)
        - 📊 **<75%**: Low confidence (exploratory)
        
        **4. Evidence Requirements**
        - Each discovery includes mechanism explanation
        - Supporting evidence from multiple sources
        - Myrion Resolution PD (Prophetic Distance) score
        - Research area classification
        
        **5. Storage & Tracking**
        - All discoveries saved to PostgreSQL database
        - Tagged with research area, confidence, timestamp
        - Accessible via this dashboard and other tabs
        """)
    
    with st.expander("🎯 Platform Roles"):
        st.markdown("""
        ### AI Platform Specializations
        
        **🧠 OpenAI GPT-5**
        - Role: Design evaluation & creative reasoning
        - Strength: Novel connections & aesthetic insights
        - Used for: TI framework expansion, philosophical proofs
        
        **🎨 Anthropic Claude Opus**
        - Role: Code quality & logical validation
        - Strength: Rigorous analysis & error detection
        - Used for: Mathematical proofs, logic verification
        
        **🔍 Perplexity AI**
        - Role: Research & web-based validation
        - Strength: Real-time information & fact-checking
        - Used for: Evidence gathering, citation validation
        
        **🌐 MagAI Platform**
        - Role: Multi-AI coordination
        - Strength: Parallel model comparison
        - Used for: Consensus building, diverse perspectives
        
        **💻 GitHub**
        - Role: Code synchronization & version control
        - Strength: Collaboration & historical tracking
        - Used for: TI codebase management, proof versioning
        """)
    
    # ===== NEXT DISCOVERY COUNTDOWN =====
    st.markdown("---")
    st.info("""
    ⏰ **Next Discovery Generation:** Every 4 hours automatically!
    
    The Bot Band runs 24/7 in the background, continuously generating insights.
    Refresh this page to see new discoveries as they appear!
    """)


if __name__ == "__main__":
    render_bot_band_dashboard()
