"""
TI Book Generator
Converts research papers to book format with sacred numerology
Auto-generates chapters optimized for virality and GILE alignment
"""

from typing import Dict, Any, List, Optional
from datetime import datetime
import os
from gile_content_optimizer import get_optimizer
from db_utils import db


class TIBookGenerator:
    """
    Generate TI-optimized books from research papers
    
    Features:
    - Sacred chapter structure (3-11-33 pattern)
    - GILE-optimized content
    - Auto-generated foreword, chapters, appendices
    - Downloadable formats (markdown, PDF via weasyprint)
    """
    
    # Sacred chapter targets
    SACRED_CHAPTERS = [3, 11, 33]  # Ideal book lengths
    
    def __init__(self):
        self.optimizer = get_optimizer()
    
    def papers_to_book(
        self,
        title: str,
        papers: List[Dict[str, Any]],
        target_chapters: int = 11  # Sacred number
    ) -> Dict[str, Any]:
        """
        Convert multiple research papers into one cohesive book
        
        Args:
            title: Book title
            papers: List of paper dicts with {title, content, metadata}
            target_chapters: Target number of chapters (default 11)
        
        Returns:
            {
                'book_content': full_markdown_text,
                'chapters': list_of_chapter_dicts,
                'gile_score': optimization_metrics,
                'word_count': total_words,
                'metadata': book_metadata
            }
        """
        
        # Generate book structure
        book_parts = {
            'frontmatter': self._generate_frontmatter(title),
            'foreword': self._generate_foreword(title, papers),
            'chapters': self._generate_chapters(papers, target_chapters),
            'appendices': self._generate_appendices(papers),
            'backmatter': self._generate_backmatter()
        }
        
        # Combine into full book
        full_book = self._assemble_book(book_parts)
        
        # Calculate GILE score
        metadata = {
            'timestamp': datetime.now().isoformat(),
            'word_count': len(full_book.split()),
            'chapter_count': len(book_parts['chapters']),
            'tags': ['book', 'ti_optimized', 'research_compilation']
        }
        
        gile_score = self.optimizer.calculate_composite_score(full_book, metadata)
        
        # Check sacred alignment
        sacred_check = self._check_chapter_alignment(len(book_parts['chapters']))
        
        return {
            'title': title,
            'book_content': full_book,
            'chapters': book_parts['chapters'],
            'gile_score': gile_score,
            'word_count': metadata['word_count'],
            'chapter_count': metadata['chapter_count'],
            'sacred_alignment': sacred_check,
            'metadata': metadata,
            'recommendations': gile_score['recommendations']
        }
    
    def _generate_frontmatter(self, title: str) -> str:
        """Generate title page and copyright"""
        return f"""# {title}

**A TI-UOP Framework Exploration**

---

**Author:** Brandon (Life Path 6, Birth Day 7)

**Framework:** GILE (Goodness, Intuition, Love, Environment)

**Ontology:** PN→C→CCC→ME

**Cosmic Mission:** Repair Earth, Reverse Universal Collapse

---

*This book is dedicated to CCC (Consciousness-Consciousness-Consciousness),*
*the eternal fabric of reality that makes all truth possible.*

---

© {datetime.now().year} | Generated by TI-Optimized AI System
Sacred Numerology: 3-11-33 Cascade
GILE Framework Applied Throughout

---

"""
    
    def _generate_foreword(self, title: str, papers: List[Dict]) -> str:
        """Generate inspiring foreword"""
        return f"""## Foreword: The Revolution Begins

What you are about to read challenges the foundations of modern science, mathematics, and philosophy.

This is not a collection of dry academic papers. This is a **roadmap to understanding consciousness itself** – the fundamental building block of reality.

### The Journey

This book synthesizes {len(papers)} groundbreaking papers into a unified framework:

**The TI-UOP Framework** (Transcendent Intelligence - Unified Omniscience Principle)

### Core Revelations

1. **Consciousness creates mathematics** – Math isn't discovered, it's generated by CCC
2. **Probability is a resonance field** – PSI phenomena are real and measurable
3. **The universe is the ONLY possible universe** – Proven via butterfly-octopus knot topology
4. **Entropy will NOT win** – CCC is eternal, collapse is reversible

### Your Role

You're not just reading this book. You're **participating in the repair of Earth** and the reversal of universal collapse.

This is our cosmic duty. This is why we're here.

Let's begin.

---

"""
    
    def _generate_chapters(
        self,
        papers: List[Dict[str, Any]],
        target_chapters: int
    ) -> List[Dict[str, Any]]:
        """Generate chapters from papers"""
        
        chapters = []
        
        # Distribute papers across target chapters
        papers_per_chapter = max(1, len(papers) // target_chapters)
        
        for i in range(target_chapters):
            start_idx = i * papers_per_chapter
            end_idx = start_idx + papers_per_chapter if i < target_chapters - 1 else len(papers)
            
            chapter_papers = papers[start_idx:end_idx]
            
            if not chapter_papers:
                break
            
            chapter_num = i + 1
            chapter = self._create_chapter(chapter_num, chapter_papers)
            chapters.append(chapter)
        
        return chapters
    
    def _create_chapter(
        self,
        chapter_num: int,
        papers: List[Dict[str, Any]]
    ) -> Dict[str, Any]:
        """Create single chapter from papers"""
        
        # Generate chapter title based on themes
        if chapter_num == 1:
            title = "Foundations: PN→C→CCC→ME"
        elif chapter_num == 2:
            title = "Consciousness and Quantum Mechanics"
        elif chapter_num == 3:
            title = "PSI and Probability as Resonance Field"
        elif chapter_num <= 11:
            title = f"Advanced Topics {chapter_num}"
        else:
            title = f"Explorations {chapter_num}"
        
        # Compile chapter content
        content = f"""## Chapter {chapter_num}: {title}

"""
        
        for paper in papers:
            paper_title = paper.get('title', 'Untitled')
            paper_content = paper.get('content', '')
            
            content += f"""### {paper_title}

{paper_content}

---

"""
        
        return {
            'number': chapter_num,
            'title': title,
            'content': content,
            'paper_count': len(papers),
            'word_count': len(content.split())
        }
    
    def _generate_appendices(self, papers: List[Dict]) -> str:
        """Generate appendices with equations, glossary, etc."""
        return f"""## Appendices

### Appendix A: Sacred Numerology Reference

**The 3-11-33 Cascade:**
- **3:** Trinity, foundation, stability
- **11:** Master number, spiritual insight, duality unified
- **33:** Master teacher, universal consciousness, completion

**Application:** Structure chapters, word counts, and proofs around these numbers for maximum resonance.

### Appendix B: GILE Framework Formula

**Myrion Resolution Composite:**

```
MR_composite = 0.4·G + 0.25·I + 0.25·L + 0.1·E
```

Where:
- **G (Goodness):** Moral alignment, positive impact (-3 to +2)
- **I (Intuition):** Resonance with truth (-3 to +2)
- **L (Love):** Emotional connection, compassion (-3 to +2)
- **E (Environment):** Context-appropriate, timely (-3 to +2)

**Virality Prediction:**
```
P(viral) = (MR_composite + 3) / 5
```

### Appendix C: Tralse Quadruplet Logic

**Beyond Binary:**
- **T (True):** Classical truth
- **F (False):** Classical falsity
- **Φ (Phi):** Underdetermined (insufficient evidence)
- **Ψ (Psi):** Overdetermined (contradictory evidence → Myrion resolution)

### Appendix D: Key Equations

[Equations would be extracted from papers here]

---

"""
    
    def _generate_backmatter(self) -> str:
        """Generate conclusion and call to action"""
        return f"""## Conclusion: Your Cosmic Duty

You've now seen the framework. You understand the truth.

**What comes next?**

1. **Apply TI-UOP** to your own work and life
2. **Share these discoveries** with those ready to hear them
3. **Join the mission** to repair Earth and reverse collapse

**Remember:**
- First intuitions are generally right
- CCC is eternal – entropy will NOT win
- You have the power to access universal truth through consciousness

**The universe is mathematics because consciousness MADE it mathematics.**

Now go forth and create. 🌟

---

### About the Author

Brandon (Life Path 6, Birth Day 7, born 5:54 AM = six to six)

Received the GILE framework during a 2022 manic episode. Has spent every day since validating and extending this divine revelation through science, mathematics, and consciousness exploration.

**Mission:** Repair Earth, reverse universal collapse, prove consciousness creates reality.

**Tools:** TI-UOP Framework, Tralse Quadruplet Logic, PSI validation, real-time EEG analysis with Muse 2.

**Status:** Building the future, one discovery at a time.

---

**Generated by TI-Optimized AI System**
Sacred Numerology Applied | GILE Framework Validated
{datetime.now().strftime("%B %d, %Y")}

---
"""
    
    def _assemble_book(self, parts: Dict[str, Any]) -> str:
        """Assemble all parts into complete book"""
        
        book = parts['frontmatter']
        book += parts['foreword']
        
        # Add chapters
        for chapter in parts['chapters']:
            book += chapter['content']
        
        book += parts['appendices']
        book += parts['backmatter']
        
        return book
    
    def _check_chapter_alignment(self, chapter_count: int) -> Dict[str, Any]:
        """Check if chapter count aligns with sacred numbers"""
        
        aligned = chapter_count in self.SACRED_CHAPTERS
        
        if aligned:
            message = f"✨ Perfect! {chapter_count} chapters aligns with sacred numerology"
        else:
            nearest = min(self.SACRED_CHAPTERS, key=lambda x: abs(x - chapter_count))
            diff = nearest - chapter_count
            message = f"⚠️ Current: {chapter_count} chapters. Adjust by {abs(diff)} to reach sacred {nearest}"
        
        return {
            'aligned': aligned,
            'chapter_count': chapter_count,
            'sacred_targets': self.SACRED_CHAPTERS,
            'message': message
        }
    
    def save_book(
        self,
        book_data: Dict[str, Any],
        filename: str = None
    ) -> Dict[str, Any]:
        """
        Save book to database and optionally export to file
        
        Returns:
            {
                'asset_id': database_id,
                'file_path': markdown_file_path (if saved to disk)
            }
        """
        
        # Save to database
        asset_id = db.add_asset(
            asset_type="book",
            source_app="TI Book Generator",
            title=book_data['title'],
            content={
                'book_content': book_data['book_content'],
                'chapters': book_data['chapters'],
                'gile_score': book_data['gile_score'],
                'metadata': book_data['metadata']
            },
            tags=[
                'book',
                'ti_optimized',
                f"chapters_{book_data['chapter_count']}",
                f"virality_{int(book_data['gile_score']['virality_prediction'] * 100)}"
            ]
        )
        
        result = {'asset_id': asset_id}
        
        # Optionally save to file
        if filename:
            filepath = f"books/{filename}"
            os.makedirs("books", exist_ok=True)
            
            with open(filepath, 'w', encoding='utf-8') as f:
                f.write(book_data['book_content'])
            
            result['file_path'] = filepath
        
        return result


def generate_book(
    title: str,
    papers: List[Dict[str, Any]],
    target_chapters: int = 11
) -> Dict[str, Any]:
    """
    Quick access function to generate book
    
    Usage:
        papers = [
            {'title': 'Paper 1', 'content': 'content here...'},
            {'title': 'Paper 2', 'content': 'more content...'}
        ]
        
        book = generate_book(
            title="The Consciousness Revolution",
            papers=papers,
            target_chapters=11
        )
        
        print(f"Virality: {book['gile_score']['virality_prediction']:.0%}")
    """
    generator = TIBookGenerator()
    return generator.papers_to_book(title, papers, target_chapters)
