"""Universal Evidence Status and Validation Maturity Enums."""

from enum import Enum

class EvidenceStatus(str, Enum):
    """Universal evidence status classifications."""
    CERTIFIED_EXACT = "CERTIFIED_EXACT"
    CERTIFIED_RECOMPUTED = "CERTIFIED_RECOMPUTED"
    HISTORICALLY_EXPLICIT = "HISTORICALLY_EXPLICIT"
    DERIVED_FROM_CERTIFIED = "DERIVED_FROM_CERTIFIED"
    DERIVED_DURING_RECOVERY = "DERIVED_DURING_RECOVERY"
    INFERRED_NOT_EXPLICIT = "INFERRED_NOT_EXPLICIT"
    PROVISIONAL = "PROVISIONAL"
    HISTORICAL = "HISTORICAL"
    SUPERSEDED = "SUPERSEDED"
    CONFLICTING = "CONFLICTING"
    SOURCE_MISSING = "SOURCE_MISSING"
    MATHEMATICALLY_INCONSISTENT = "MATHEMATICALLY_INCONSISTENT"

class ValidationMaturityTier(str, Enum):
    """Validation maturity tier levels."""
    TIER_0_CONCEPTUAL = "TIER_0_CONCEPTUAL"
    TIER_1_IMPLEMENTED = "TIER_1_IMPLEMENTED"
    TIER_2_INTERNAL_VALIDATION = "TIER_2_INTERNAL_VALIDATION"
    TIER_3_EXTERNAL_BENCHMARK = "TIER_3_EXTERNAL_BENCHMARK"
    TIER_4_INDEPENDENT_REPLICATION = "TIER_4_INDEPENDENT_REPLICATION"
    TIER_5_PEER_REVIEWED_REPLICATION = "TIER_5_PEER_REVIEWED_REPLICATION"

class ResolutionMode(str, Enum):
    """Registry resolution security modes."""
    CERTIFIED_ONLY = "CERTIFIED_ONLY"
    CERTIFIED_AND_DERIVED = "CERTIFIED_AND_DERIVED"
    RESEARCH_ALL = "RESEARCH_ALL"
